AGIP-94: Wearables Rental (Implementation Proposal)
aavegotchi/aavegotchi-contracts pull request #230
Opened 2023-12-01 20:04 UTC by karacurt

As part of AGIP-94, this PR aims to enable Aavegotchi Wearable Rentals using a role-based delegation feature. In this implementation, users intending to rent wearables would go through the following flow:

* NFT owner calls the [`grantRoleFrom`](https://github.com/OriumNetwork/aavegotchi-contracts/blob/f7ef1c127799f3d92e58762dd01ef339acade784/contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol#L50) function to delegate their wearables to a given user (Borrower). The NFTs are deposited in the Aavegotchi Diamond contract with no association with any given Aavegotchi.
* The Borrower calls the new [`equipDelegatedWearables`](https://github.com/OriumNetwork/aavegotchi-contracts/blob/f7ef1c127799f3d92e58762dd01ef339acade784/contracts/Aavegotchi/facets/ItemsFacet.sol#L202) function to equip delegated wearables on an Aavegotchi they own. Since the NFT is already deposited, this step only creates the Wearable<>Aavegotchi association.
* After the expiration date, the owner can withdraw the wearables back, or delegate to a new user.

 The Implementation features:
* A new facet to handle ERC-1155 delegations ([`ItemsRolesRegistryFacet.sol`](https://github.com/OriumNetwork/aavegotchi-contracts/blob/ON-484-stf-registry/contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol)).
* A new [`equipDelegatedWearables`](https://github.com/OriumNetwork/aavegotchi-contracts/blob/f7ef1c127799f3d92e58762dd01ef339acade784/contracts/Aavegotchi/facets/ItemsFacet.sol#L202) function, responsible to allow borrowers to equip rented wearables.
* A [`revokeRolefrom`](https://github.com/OriumNetwork/aavegotchi-contracts/blob/f7ef1c127799f3d92e58762dd01ef339acade784/contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol#L106) function that allows NFT Owners to withdraw rented wearables.

2023-12-13 14:47 UTC, ernanirst requested changes

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +    function _grantOrUpdateRole(RoleAssignment memory _grantRoleData) internal {
```suggestion
    function _grantOrUpdateRole(RoleAssignment calldata _grantRoleData) internal {
```

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +        }
Move deletes to unequip function, and rename function to `_unequipDelegatedWearable`

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +    function _unequipWearable(uint256 _gotchiId, uint256 _wearableToUnequip, uint256 _balanceToUnequip) internal {
```suggestion
    function _unequipDelegatedWearable(uint256 _gotchiId, uint256 _tokenIdToUnequip, uint256 _balanceToUnequip) internal {
```

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +    function withdraw(uint256 _depositId) public onlyOwnerOrApproved(s.itemsDeposits[_depositId].grantor, s.itemsDeposits[_depositId].tokenAddress) {
```suggestion
    function withdraw(uint256 _depositId) external onlyOwnerOrApproved(s.itemsDeposits[_depositId].grantor, s.itemsDeposits[_depositId].tokenAddress) {
```

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +        delete s.itemsDeposits[_depositId];
```suggestion
        delete s.itemsDeposits[_depositId];
        delete s.itemsRoleAssignments[_depositId];
```

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +        _transferFrom(address(this), _depositInfo.grantor, _depositInfo.tokenAddress, _depositInfo.tokenId, _depositInfo.tokenAmount);
Verify if the wearable is equipped before withdrawing. If equipped, call `_unequipDelegatedWearable`

2023-12-13 14:47 UTC, ernanirst commented on contracts/Aavegotchi/facets/ItemsRolesRegistryFacet.sol
> +    }
Remove this function, it's probably already implemented somewhere in the Aavegotchi Diamond contract. We need to identify where is implemented, and simply add `ISftRolesRegistry`

2023-12-13 17:30 UTC, ernanirst requested changes

2023-12-13 20:58 UTC, karacurt commented on contracts/Aavegotchi/facets/ItemsFacet.sol
> +        uint256[EQUIPPED_WEARABLE_SLOTS] memory _depositIds
it can't be calldata to keep the old `equipWearable` function working (it creates a empty depositIds array in memory)

2023-12-21 21:33 UTC, ernanirst requested changes

2023-12-22 21:14 UTC, closed without merging